title: Numbers and Brightness
description: User guide for Numbers and Brightness analysis
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
markdown: kramdown
baseurl: "/Numbers-and-brightness"
url: "https://JvB22.github.io"
include:
- docs
